version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easychatdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: UTC
    command: --default-time-zone='+00:00'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: easychat-backend
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: 1234
      DB_NAME: easychatdb

volumes:
  mysql-data:
